### ISSUE TITLE
Help getting this to work?

### ISSUE THREAD

**Issue by AmbientMalice** [purplemarshmallow/z64#1]
I was interested in testing the improvements you've made to this fork, but I can't get PJ64 or mupen64plus to recognise the dlls the Visual Studio Project file produces.

**Comment by purplemarshmallow** [comment]
This plugin is not compatible with mupen64plus
With PJ64 you need to put glew32.dll and SDL.dll in the emulator's directory. I updated glew so you need the latest version (1.13.0.0)
Try the dlls from here https://drive.google.com/file/d/0B7Y6r4SpC_QQdzVuWURyMmkxX2M/view?usp=sharing
But but z64gl from this download will run very slow because it's the experimental angrylion fb build.

I'm planning to get rid of dependencies or link them statically

**Comment by AmbientMalice** [comment]
Ah, I see. I was missing SDL.dll. Thanks. I thought the plugin was Zilmar spec, anyway, looking at the source, but I wasn't 100% sure.
