### ISSUE TITLE
super bowling framebuffer effects

### ISSUE THREAD

**Issue by purplemarshmallow** [purplemarshmallow/z64#31]
I want to get this working. Buffers are overlapping in this game. z64gl currently just removes overlapping buffers. From what I can see this effect should work if the content of the old buffer is copied to the new buffer before removing it (exactly at this point https://github.com/purplemarshmallow/z64/blob/master/src/rgl.cpp#L646 ) 

I can't find a good way to copy from one texture to another texture. Does someone who knows Opengl better have an idea? Maybe @mudlord ?

This image is not quite correct, first Buffer 2 is rendered and then Buffer 1 is rendered on top of that
![3ca9535c-c9be-11e5-929a-4c31f5d8e2c1](https://cloud.githubusercontent.com/assets/7283660/14286393/31aeef9e-fb4f-11e5-8e88-2473472100c2.jpg)

**Comment by cxd4** [comment]
Traditionally, I think the original way is to copy with glCopyTex[Sub]Image2D from GL 1.1, but I have not tested this way.  Theoretically there is glCopyPixels from 1.0, which was removed from later specs.

**Comment by purplemarshmallow** [comment]
Thanks for the hint
I tried this code

```
xglBindFramebuffer(GL_FRAMEBUFFER_EXT, rBuffers[j].fbid);
glBindTexture(GL_TEXTURE_2D, buffer.texid);
glCopyTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, 0, 0, buffer.fboWidth, buffer.fboHeight, 0);
```

I get different results results in windowed and fullscreen mode. I think I'm on the right way. Guess I have to calculate values based on the addresses to get it correctly

![1](https://cloud.githubusercontent.com/assets/7283660/14295152/b9efdac4-fb74-11e5-8777-2da8f223d17f.jpg)
![2](https://cloud.githubusercontent.com/assets/7283660/14295153/b9f1ebe8-fb74-11e5-9dd0-bb789b77845e.jpg)

**Comment by cxd4** [comment]
Err, right, I should have added that (x, y) parameters to those calls are in client-side window space coordinates, rather than source texture raster coordinates.  (I don't remember if there are any old, surviving commands for using the latter.)

You might multiply the N64 frame-buffer-based (x, y) by a ratio based on the current width of the GL viewport, as obtained by `glGetIntegerv(GL_VIEWPORT, &viewport_coordinates_array[0]);`

**Comment by purplemarshmallow** [comment]
I think this code should always work in theory

```
int offset = int(rBuffers[j].addressStart) - int(buffer.addressStart);
int x = offset % buffer.width;
int y = offset / buffer.width;
y = -y/2;
x = -x/2;
xglBindFramebuffer(GL_FRAMEBUFFER_EXT, rBuffers[j].fbid);
glBindTexture(GL_TEXTURE_2D, buffer.texid);
glCopyTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, x, y, buffer.fboWidth, buffer.fboHeight, 0);
```

Super Bowling menu: perfect
![1](https://cloud.githubusercontent.com/assets/7283660/14329850/ba844e06-fc3d-11e5-8211-a0505bdc638e.jpg)

Super Bowling ingame: not so good. I debugged it
offset is always +/-320
y is always 0
x is alwasy 0
Not sure why/what's going on
![2](https://cloud.githubusercontent.com/assets/7283660/14329890/f0e2851c-fc3d-11e5-8cb7-543b3c55ad49.jpg)

NASCAR 2nd player now shows something
better than before but not quite there yet
![3](https://cloud.githubusercontent.com/assets/7283660/14330067/086dbc6e-fc3f-11e5-8131-9b1907dc2f11.jpg)

**Comment by purplemarshmallow** [comment]
I got it, this code is correct

```
            int offset = buffer.addressStart - rBuffers[j].addressStart;
            int x = (offset/2) % buffer.width;
            int y = (offset/2) / buffer.width;

            xglBindFramebuffer(GL_FRAMEBUFFER_EXT, rBuffers[j].fbid);
            glBindTexture(GL_TEXTURE_2D, buffer.texid);
            glCopyTexImage2D(GL_TEXTURE_2D, 0, GL_RGBA, x, y, buffer.fboWidth, buffer.fboHeight, 0);
```

Super Bowling now fixed, fully working with z64gl. NASCAR still not working unfortunately.

**Comment by purplemarshmallow** [comment]
> Err, right, I should have added that (x, y) parameters to those calls are in client-side window space coordinates, rather than source texture raster coordinates. (I don't remember if there are any old, surviving commands for using the latter.)
> 
> You might multiply the N64 frame-buffer-based (x, y) by a ratio based on the current width of the GL viewport, as obtained by glGetIntegerv(GL_VIEWPORT, &viewport_coordinates_array[0]);

@cxd4 I think I need client-side window space coordinates, or do I miss something?

**Comment by cxd4** [comment]
They just need to be scaled to the size of the viewport, I think.

So if you're running z64gl in windowed mode in a 320x240 GL viewport (and emulator window size), it may share the same dimensions as the frame buffer pitch (if VI_WIDTH_REG is 320) with no extra adjustment necessary.  Somewhere in the plugin for changing resolutions or going to fullscreen is probably some calls to glViewport(_x_, _y_, _width_, _height)_...you can query what these four parameters were last set to in a call to glViewport with `glGetInteverv(GL_VIEWPORT, (GLint *));`.

By the way, this isn't important I think, but I know it's faster to do sub-texture updates using glTexSubImage2D instead of glTexImage2D...I am not experienced with the copy versions of these functions but you may decide to investigate performance changes from using glCopyTex**Sub**Image.

**Comment by purplemarshmallow** [comment]
I noticed something really bad. It only works with a Nvidia GPU. It does not work on intel. I also tried the Mesa3D driver from #18 and that one does not work either. Setting the window to 320x240 does not help. I always get the same result. Nvidia works, everything else not.

Not sure how this is possible. I guess my code is wrong but Nvidia's driver does something weird to make it work?

With intel I get this. Part of the image is correct but part of the image is black. Looks like glCopyTexImage can erase part of the image unless you have a Nvidia card?
![1](https://cloud.githubusercontent.com/assets/7283660/14368670/8bf3d51a-fd1f-11e5-9e42-d7c94e7ae758.jpg)

**Comment by cxd4** [comment]
Maybe your card doesn't support NPOT or something.

Check the return value of glGetError() for any nonzero error codes, and try experimenting with glCopyTexSubImage instead of glCopyTexImage.  (The former updates a sub-texture region within a previously allocated texture object boundary and is generally faster anyway.)

**Comment by ghost** [comment]
yeah, glCopyTexSubImage2D should be much faster once the original framebuffer texture is allocated. You could have used glBlitFramebuffer to do this also assuming you are using OpenGL 3. Which I guess is not a option I guess.

**Comment by purplemarshmallow** [comment]
Real life got in my way with this
But now I got it working on all GPUs using glCopyTexSubImage2D
Thanks for the help!
